### ISSUE TITLE
希望可以恢复【网页搜索】功能

### ISSUE THREAD

**Issue by f59375543** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#101]
在3.6.5时仍然支持，但是升级到3.7以后失去这个功能

**Comment by Justwen** [comment]
网页搜索是什么功能？

**Comment by f59375543** [comment]
> 网页搜索是什么功能？

选中文字后，可以直接点击搜索，然后跳转到浏览器的搜索引擎，升级到3.7以后就没有这个按钮了

![20220516183215](https://user-images.githubusercontent.com/43315911/168574338-dad4c05e-8274-4fad-ab03-e8ecc0802cb3.jpg)

**Comment by Justwen** [comment]
我的手机还支持，是你的系统问题吧，或者weview组件的问题

**Comment by Justwen** [comment]
升级target 30后就没了，这个是系统行为，客户端没法控制

**Comment by f59375543** [comment]
> 

我现在是安卓12，使用3.6.5版本仍然可以使用这个功能
