### ISSUE TITLE
How to build floatingactionmenu.aar?

### ISSUE THREAD

**Issue by linsui** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#102]
It has some more class than the one I built from https://github.com/Justwen/android-floating-action-button. How to build the same aar? Thanks!

**Comment by Justwen** [comment]
可能是我本地打的aar，年代过于久远了

**Comment by linsui** [comment]
使用上游的和你的 https://github.com/Justwen/android-floating-action-button 编译的 aar 都会遇到缺少符号错误。

```
nga_phone_base_3.0/src/main/java/sp/phone/view/behavior/ScrollAwareFamBehavior.java:17: error: cannot find symbol
public class ScrollAwareFamBehavior extends com.getbase.floatingactionbutton.ScrollAwareFamBehavior {
                                                                            ^
  symbol:   class ScrollAwareFamBehavior
  location: package com.getbase.floatingactionbutton
1 error
4 warnings
```

这个类我没有找到。

**Comment by linsui** [comment]
请问可以把本地没有发布的更改发布出来吗？我在给 F-Droid 打包的时候需要从源码编译依赖。谢谢！

**Comment by Justwen** [comment]
估计我当时没push，这都是4年前了，源码早丢了
反正这个aar也没几个类，也没混淆，直接手动复制出来吧

**Comment by linsui** [comment]
请问需要怎么做？需要反编译一下吗？可以麻烦你将提取出来的源码推送到仓库吗？或者我开一个 PR？

**Comment by Justwen** [comment]
你把aar直接用as打开就能看到源码了

**Comment by linsui** [comment]
我用 jadx 反编译了一下，除了添加了两个 java 文件应该没什么其他改动。我试试编译有没有问题，没问题的话我开个 PR 推回你的仓库。
