### ISSUE TITLE
帖子内字体不适配系统字体

### ISSUE THREAD

**Issue by IUWU-0824** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#103]
帖子列表的字体是系统字体，帖子内字体是默认的，看着好难受![Screenshot_2022-05-06-15-48-04-214_gov.anzong.androidnga.jpg](https://user-images.githubusercontent.com/85593684/167089892-6f779522-d35b-4066-b72c-a56e8fcd7e23.jpg)![Screenshot_2022-05-06-15-48-01-395_gov.anzong.androidnga.jpg](https://user-images.githubusercontent.com/85593684/167089897-5a828e97-6186-4ee2-96e3-531c635637e4.jpg)

**Comment by Justwen** [comment]
帖子详情不支持自定义系统全局字体，系统限制，官方版也不支持
