### ISSUE TITLE
所有帖子回复都变成0了

### ISSUE THREAD

**Issue by Typeve** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#107]
![Screenshot_2022-08-26-12-14-20-591_gov.anzong.androidnga.jpg](https://user-images.githubusercontent.com/45506880/186820730-325f0bb0-a7f4-467b-b06b-00af894ceb7e.jpg)

帖子内容中也看不到回复

**Comment by ElementBridge** [comment]
我这边也是

**Comment by Typeve** [comment]
> 我这边也是

是nga的问题，pc上也是没有回复

**Comment by oxyzchen** [comment]
换个域名，用nga.178.com 试试

**Comment by wx40217** [comment]
同 域名换成178就好了

**Comment by machine-doll** [comment]
> 同 域名换成178就好了

这个客户端有办法换吗？

**Comment by zynowhere** [comment]
> > 同 域名换成178就好了
> 
> 这个客户端有办法换吗？

设置里面可以改

**Comment by xiaoyaoyuxin** [comment]
现在换成178也不行了。

**Comment by Justwen** [comment]
支持自定义UA
