### ISSUE TITLE
提供使用系统浏览器而非内置浏览器打开的功能

### ISSUE THREAD

**Issue by Aqua-Dream** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#108]
希望提供一个选项，能选择用默认用系统浏览器打开还是用内置浏览器打开。目前的内置浏览器功能过于简单（例如无法唤起其他应用），无法满足需求。

**Comment by Aqua-Dream** [comment]
例如和微信一样，右上角三个点，可以选择用指定外部浏览器打开。场景是帖内有外部应用的链接，无法唤起，需要自行复制去浏览器打开，比较麻烦。

**Comment by Justwen** [comment]
比如哪个帖子和连接？

**Comment by Justwen** [comment]
已修复

**Comment by Aqua-Dream** [comment]
谢谢！最近发现NGA内置浏览器一直用桌面模式显示，以至于不手动放大完全看不清，不知道是什么原因，外置浏览器则正常。请问可否提供一个开关，选择后自动用外置浏览器打开而非内置？

**Comment by Aqua-Dream** [comment]
外置浏览器
![lQDPJxbiTFlGZcHNBQDNAyGwrgGcQPPAcF4Dc9VVmkDhAA_801_1280](https://user-images.githubusercontent.com/17526818/202613226-1eb40f92-cace-4f9a-971a-c4f6774e1a9d.jpg)

内置浏览器
![lQDPJxbiTFlGa47NBP_NAoawjJHVlNimGjsDc9VWG4DhAA_646_1279](https://user-images.githubusercontent.com/17526818/202613256-5a4910c7-8e5e-428f-91fb-4eab28d2d18c.jpg)

**Comment by Justwen** [comment]
应该是用了PC端的UA，现在用默认UA可以看到回复了
