### ISSUE TITLE
下拉版面列表出现For input string错误

### ISSUE THREAD

**Issue by reichelite** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#122]
点进版面后一直下拉帖子列表会出现“For input string: #anony xxxx”错误，xxxx似乎是一串校验码
![Screenshot_20221202-173425_NGA](https://user-images.githubusercontent.com/39641238/205263462-c1842bd2-c6a5-4494-9097-a6d57de40421.jpg)

**Comment by reichelite** [comment]
版本是3.8.3

**Comment by Awakumori** [comment]
同样的问题,进入网事杂谈板块偶尔会报错。另外那个#anony字符串代表的是某个匿名帖子的用户uid,不知道这个bug是怎么发生的。

**Comment by xc1988** [comment]
我也遇到了就往事杂谈会有这个问题
其他板块还没遇到

**Comment by leifan8440** [comment]
求修复

**Comment by KIrayamoto** [comment]
在其他板块也遇到了，似乎是随机发生

**Comment by yukiloh** [comment]
的确是最近遇到的,关注

**Comment by acer-xhy** [comment]
TopicConvertFactory类的184行解析判断修改下就好了
            String authorId = tBean.getAuthorid();
            if (author.startsWith("#anony_")) {
                pageInfo.setAnonymity(true);
                pageInfo.setAuthor(getAnonymityName(tBean.getAuthor()));
            } else if (!TextUtils.isEmpty(authorId) && authorId.startsWith("#anony_")) {
                pageInfo.setAnonymity(true);
                pageInfo.setAuthor(getAnonymityName(authorId));
            } else {
                pageInfo.setAuthorId(Integer.parseInt(authorId));
                pageInfo.setAuthor(tBean.getAuthor());
            }

**Comment by Justwen** [comment]
谷歌市场要求升target31才能更新，暂时没时间做
大家需要的可以直接去这里下
https://github.com/Justwen/NGA-CLIENT-VER-OPEN-SOURCE/releases/tag/3.8.4

**Comment by Justwen** [comment]
已上传google play
