### ISSUE TITLE
Move to modern AGP

### ISSUE THREAD

**Issue by FantasqueX** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#134]
Hi, thank you for this great project. I wonder is it possible to upgrade AGP to more modern version which makes it possible to use the latest Android Studio to develop and makes the building progress faster.

If you agree with me, I'll send a patch to solve this issue.

**Comment by Justwen** [comment]
High AGP version requires Java 11，while my MBP only run with Java 8

**Comment by FantasqueX** [comment]
As far as I know, homebrew supports openjdk@11 on x86_64 and aarch64. Android Studio supports setting JDK for specific project. You can still use openjdk@8 as system JDK and use openjdk@11 as JDK of this project.

**Comment by Justwen** [comment]
AGP升级到4.2.2了，目前来看没有问题

**Comment by FantasqueX** [comment]
Thanks for your work moivng to AGP 4.2.2. Still look forward to a more recent version. The build process is quite slow currently😭

**Comment by Justwen** [comment]
更高的AGP版本需求更高的AS版本，暂不考虑提升AGP至7.0以上

**Comment by FantasqueX** [comment]
感谢更新 AGP 7.0.4 https://github.com/Justwen/NGA-CLIENT-VER-OPEN-SOURCE/commit/cdf08e1becdf8cd55a44942d3ab9e22a69a35b2d

此 issue 可以关闭了。
