### ISSUE TITLE
在 Github 添加 3.8.5 release

### ISSUE THREAD

**Issue by FantasqueX** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#141]
我注意到 [commit](https://github.com/Justwen/NGA-CLIENT-VER-OPEN-SOURCE/commit/96922c7ab174223f0ab9f88bfc549e3c1e7d1de1) 提升了版本号，发了新版。是否可以推一个 git tag 或者 GitHub release？谢谢！

**Comment by Justwen** [comment]
done
