### ISSUE TITLE
[功能请求]更方便的点赞

### ISSUE THREAD

**Issue by mlzzen** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#142]
希望能像这个版本的[开源NGA客户端](https://gitee.com/sjtuYricky/NGA-CLIENT-VER-OPEN-SOURCE)一样，改成这样点赞
![Snipaste_2023-02-16_08-39-23](https://user-images.githubusercontent.com/11664505/219228243-b7b6f883-ab8c-451c-8941-2d805707a68e.jpg)

**Comment by Justwen** [comment]
已合并代码
