### ISSUE TITLE
NGA开源版功能建议

### ISSUE THREAD

**Issue by Biu-Bong** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#15]
建议增加一个启动页面的功能，打开NGA可以直接进入自己收藏的板块，可以通过左右滑动切换已收藏的板块

**Comment by 1078249029** [comment]
建议增加版头功能，感谢

**Comment by Justwen** [comment]
版头需要nga支持，客户端做不了，问题太过久远，关掉了

**Comment by 1078249029** [comment]
> 版头需要nga支持，客户端做不了，问题太过久远，关掉了

相关问题我已经加群反馈了，我的需求现已解决，感谢回复
