### ISSUE TITLE
使用内置web浏览帖子，登录时无法显示图形验证码

### ISSUE THREAD

**Issue by History-exe** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#153]
访问部分帖子，自动跳转内部web浏览，这个功能没问题。已经在UA里添加了“NGA_Offical”

但遇到需要web登录的帖子时，输入了帐号密码，提示缺少图形验证码。因为没有弹出验证码，也没有输入验证码的位置导致无法浏览帖子。提示如图：
![图片](https://user-images.githubusercontent.com/33642965/223896053-971c5a51-59df-447a-9e0a-9a35cdab6b56.png)

**Comment by Drangleic71** [comment]
我也遇到了这个问题。
之前跳转内置web访问时，可以正常显示验证码并登录，从而继续访问帖子。但是现在无法在内置web中登录，提示缺少图片验证码。

**Comment by zhixia22** [comment]
把最后的/NGA_Offical删掉就能显示验证码了，
而且现在去掉了也不影响正常访问的

**Comment by History-exe** [comment]
> 把UA里后加的/NGA_Offical删掉就能显示验证码了， 而且现在去掉了也不影响正常访问的

好的，确实解决了问题，这个issue我关闭了。
