### ISSUE TITLE
希望加入签到功能

### ISSUE THREAD

**Issue by pkuzyj** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#156]
网页版的油猴脚本已经可以实现自动签到，希望可以在新版本中集成这个功能，方便在一些版面回帖

**Comment by mlzzen** [comment]
重复 #19

**Comment by pkuzyj** [comment]
NGA Agent

**Comment by mlzzen** [comment]
> NGA Agent

在最新的PR中已经实现这个功能了。 https://github.com/Justwen/NGA-CLIENT-VER-OPEN-SOURCE/pull/163

**Comment by Justwen** [comment]
下个版本发布
