### ISSUE TITLE
添加关注在哪里？

### ISSUE THREAD

**Issue by specked2527** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#160]
没有找到添加关注按钮

**Comment by mlzzen** [comment]
关注接口好像用的官方客户端接口，没有网页版。而且官方客户端接口是有加密的。

**Comment by mlzzen** [comment]
好消息，网页版现在可以关注，以及查看关注列表，以及关注的动态了。

![image](https://github.com/Justwen/NGA-CLIENT-VER-OPEN-SOURCE/assets/11664505/af34170c-c266-449f-a144-3560d3b2471d)

![image](https://github.com/Justwen/NGA-CLIENT-VER-OPEN-SOURCE/assets/11664505/c6ed9bda-21d5-4e45-8461-a9c30c501be0)

**Comment by mlzzen** [comment]
关注动态以及关注列表以及可以用了，关注功能暂不能在网页版上用。
