### ISSUE TITLE
听说谷歌商店已经更新到3.8.6，这边可以同步一下吗

### ISSUE THREAD

**Issue by Aqua-Dream** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#161]
手机没有谷歌框架，目前3.8.5有发帖失败问题，希望release及时更新，感谢！

**Comment by reichelite** [comment]
同样问题，发帖失败且看帖时403与后台抽风频率异常增高

**Comment by specked2527** [comment]
@Aqua-Dream @reichelite  :interrobang: 你不提醒 我都不知道😓
[免商店](https://apkcombo.com/zh/national-gay-alliance客户端开源版/gov.anzong.androidnga/download/apk)

**Comment by Justwen** [comment]
已上传
