### ISSUE TITLE
[功能请求] 是否可以提供更改User Agent的选项

### ISSUE THREAD

**Issue by Msopopop** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#17]
由于部分版面暂时变成官方版app限定（比如水区 -7），经查只需将UA更改为类似于

> Nga_Official/3.3.1 (Xiaomi;Android 6.1.0)

即可访问。目前开发团队是否有意愿在app内添加可让用户自行更改UA的选项？

**Comment by Justwen** [comment]
临时增加UA，暂不提供自定义UA的功能，下载地址 https://github.com/Justwen/NGA-CLIENT-VER-OPEN-SOURCE/releases
