### ISSUE TITLE
软件权限中无手机存储导致在部分系统内无法上传/保存图片

### ISSUE THREAD

**Issue by KisinYouki** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#172]
因应用在部分系统（flyme 10.5）内无手机存储权限选项，导致无法上传/保存图片
![S31220-11134431_com android settings](https://github.com/Justwen/NGA-CLIENT-VER-OPEN-SOURCE/assets/39112066/5a8a3f0a-e8bc-45a8-8da1-a08a157195ab)
![S31220-11135564_com android permissioncontroller](https://github.com/Justwen/NGA-CLIENT-VER-OPEN-SOURCE/assets/39112066/bd306b57-6103-4cbd-9b49-a99c99367b50)

**Comment by kljjh** [comment]
可以使用app ops、权限狗等软件强制给它读取存储空间权限 给权限后魅族21测试正常
![S31222-16005014_rikka appops](https://github.com/Justwen/NGA-CLIENT-VER-OPEN-SOURCE/assets/29812342/dfb4bebb-e8f3-4373-8361-ec75de9a4382)
![S31222-16020924_com android providers media module](https://github.com/Justwen/NGA-CLIENT-VER-OPEN-SOURCE/assets/29812342/bc5be015-bdeb-4386-a88d-87717816196f)

**Comment by ssthe** [comment]
我也有同样的问题，一开始gplay版本拉下来权限不正常没法发图，手动从GitHub拉3.8.6版本的apk然后安装3.8.6版本有正常权限，结果gplay自动更新一下直接恢复这个权限状态

**Comment by Justwen** [comment]
已修复
