### ISSUE TITLE
无法打开版面 syntax error expected{, actual 4

### ISSUE THREAD

**Issue by seeroffish** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#177]
![Uploading Screenshot_2024-03-31-10-50-48-95_2348c57626e5d1a6310a7863c0b4fcae.jpg…]()

**Comment by Qiaofanxing** [comment]
遇见同样问题，还会导致全局搜索报错

**Comment by Justwen** [comment]
已修复，github上已上传新版本
