### ISSUE TITLE
大概是个bug🤔

### ISSUE THREAD

**Issue by Koikaede** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#22]
版本为play上的3.3.3，3.3.2也是一样
在浏览公主连结子板块时会报错
![IMG_20200525_142403](https://user-images.githubusercontent.com/65886763/82785296-eaceef00-9e94-11ea-91e9-2587878dd6a9.jpg)

**Comment by Justwen** [comment]
下个版本修复
