### ISSUE TITLE
Bug：收藏楼层中的帖子不能删除

### ISSUE THREAD

**Issue by JimmyJuan** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#24]
最近增加了收藏某一楼发言功能。
有两个问题：
1，对于已经养成习惯的老用户，原来点帖子第二个是点赞，现在是收藏。动不动就把帖子收藏了。
2，收藏了之后无法删除收藏。

ps：版本是3.3.6

**Comment by Justwen** [comment]
不能收藏的问题下个版本修复，可以临时去网页版删除
