### ISSUE TITLE
建议把上传图片时Timeout时间延长一下

### ISSUE THREAD

**Issue by mikelei1997** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#29]
您好，首先很感谢一直在维护这个客户端！我是海外用户，一直在用这个版本的客户端，感觉很好。
有个问题是上传图片时有九成概率提示timeout，在网页版或者官方客户端上传就没这问题。
我个人判断是开源版客户端timeout时间设太短导致还没传完就被打断了，我知道海外往国内传图会比较慢所以不介意多等一会的。

**Comment by Justwen** [comment]
延迟到5分钟下个版本修复
