### ISSUE TITLE
帖子内容无法正常显示

### ISSUE THREAD

**Issue by sgkoishi** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#34]
安卓10，客户端版本3.4.1
![](https://cdn.discordapp.com/attachments/426539244908052491/757431135105187840/tempFileForShare_20200920-194031.jpg)
点击回帖的那个箭头时输入栏里会自动出现帖子内容（但回复主楼时无效），因此暂且估计是无法显示

**Comment by Justwen** [comment]
100%复现？

**Comment by sgkoishi** [comment]
> 
> 
> 100%复现？

是的，我目前所有帖子都是这样。下载来源是Google Play，尝试过重新安装/登出登入但都没有变化。

**Comment by sgkoishi** [comment]
~~然后在安卓系统更新后的第二天早上打开时突然好了... 有点迷，关了~~
