### ISSUE TITLE
建议获取用户信息改为UID而不是用户名

### ISSUE THREAD

**Issue by asoulist** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#37]
rt，比如我的用户名里含有一个“竜”字，在app里就无法显示，点击任何和自己有关的功能都会弹出错误2048查无此人，估计其他ID含有非简中字符的也会出问题
建议改为用UID获取，或者扩大一下显示用字符集

**Comment by misakamikoton** [comment]
I have the same problem, cant search my replies by using username. Use uid is better.

**Comment by Justwen** [comment]
改成uid有兼容性问题，用id查和用户名查返回的结果居然不一样

**Comment by misakamikoton** [comment]
那就扩大字符集吧

**Comment by Justwen** [comment]
已修复
