### ISSUE TITLE
上传图片附件好像出问题了？

### ISSUE THREAD

**Issue by milkum** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#38]
![Screenshot_2020-11-08-02-49-16-68_2348c57626e5d1a6310a7863c0b4fcae](https://user-images.githubusercontent.com/74113631/98449263-0c831080-216d-11eb-94a0-2a01f4db12ef.jpg)
错误提示，好像是泥潭爆炸后修改地址的原因？

**Comment by Justwen** [comment]
接口变了，已更新
