### ISSUE TITLE
只看此人时帖子的某些页数载入失败

### ISSUE THREAD

**Issue by hoshinokiseki** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#70]
版本：3.6.5
问题描述：在只看此人的情况下，某些页数会无法载入，且app上方的页数会偶尔消失，需要下拉刷新才会出现。
帖子链接：http://bbs.nga.cn/read.php?tid=27234969

**Comment by Justwen** [comment]
没复现，复现重新提吧
