### ISSUE TITLE
近期经常出现的加载失败问题

### ISSUE THREAD

**Issue by g2770824420** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#93]
![64959e49eb0ac107](https://user-images.githubusercontent.com/40188565/160237083-8ccb8858-8a36-413d-b9c7-4279a1cc6766.jpg)
3.7.3版本虽然调价了默认浏览器打开但始终不方便，能否彻底解决此问题呢

**Comment by Justwen** [comment]
NGA后台问题，无法彻底解决

**Comment by mikelei1997** [comment]
API出问题 客户端没办法的

**Comment by g2770824420** [comment]
感谢回答
