### ISSUE TITLE
点击帖子后提示nga后台抽风了

### ISSUE THREAD

**Issue by shadowborder** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#95]
经常出现nga后台抽风了，请使用内置浏览器打开。好像是随机发生的，但是频率还挺高。
![Screenshot_2022-04-08-17-53-43-970_gov anzong androidnga](https://user-images.githubusercontent.com/75469348/162587688-57985378-baba-4244-9894-533e29866b1f.jpg)

**Comment by shadowborder** [comment]
手机小米9，安卓版本11，app版本3.7.3

**Comment by shadowborder** [comment]
不同时间段出现的频率也不一样

**Comment by yukiloh** [comment]
相同的问题,使用右上角"使用内置浏览器查看"并没有什么用
其实可以通过切换账号来查看帖子
希望在进入帖子后的右上角,也就是"使用内置浏览器查看"的下方添加切换账号的功能

**Comment by LitCcc** [comment]
这个应该是NGA那边的问题，如果NGA不修复没什么办法

**Comment by Justwen** [comment]
这个没有根本解决版本，只能绕过去
1、浏览器打开
2、多账号切换
下个版本支持
