### ISSUE TITLE
无法收藏 [PS4]女神异闻录 这个板块

### ISSUE THREAD

**Issue by Mike1117** [Justwen/NGA-CLIENT-VER-OPEN-SOURCE#99]
Google play版本3.7.5 三星S21Ultra OneUI 4.1

**Comment by Justwen** [comment]
具体是什么问题，我试了没复现

**Comment by Mike1117** [comment]
目前已经解决了。之前不知道为什么，于首页点击游戏专版，然后下拉找到女神异闻录版块，进入后点击收藏后它不会进入我的收藏页面
